# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13hqAwdmQovhoiCGYuj69px51Up4evAGE
"""

#1-1
import pandas as pd

df = pd.read_csv('/content/edu_bigdata_imp1.csv', encoding='big5',low_memory=False)

df_filtered = df[df['PseudoID'] == 39]

unique_values = df_filtered['dp001_review_sn'].unique()

print(len(unique_values))

#1-2
import pandas as pd

df = pd.read_csv('/content/edu_bigdata_imp1.csv', encoding='big5', low_memory=False)

df_filtered = df[df['PseudoID'] == 39]

df_filtered = df_filtered.dropna(subset=['dp001_question_sn'])

unique_values = df_filtered['dp001_question_sn'].unique()

print(len(unique_values))

#2-1
import pandas as pd

df = pd.read_csv('/content/edu_bigdata_imp1.csv', encoding='big5', low_memory = False)

df_filtered = df[df['PseudoID'] == 281]

df_filtered = df_filtered.dropna(subset=['dp001_indicator'])

df_unique = df_filtered.drop_duplicates(subset='dp001_video_item_sn')

print(df_unique[['dp001_video_item_sn', 'dp001_indicator']])

#2-2
import pandas as pd

df = pd.read_csv(
    "/content/edu_bigdata_imp1.csv",
    encoding="big5",
    low_memory=False,
)

df_filtered = df[(df["PseudoID"] == 281) & (df["dp001_prac_score_rate"] == 100)]

df_filtered = df_filtered.dropna(subset=["dp001_prac_date"])

df_unique = df_filtered.drop_duplicates(subset="dp001_prac_score_rate")

print(len(df_filtered))

#3-1
import pandas as pd

df = pd.read_csv(
    "/content/edu_bigdata_imp1.csv",
    encoding="big5",
    low_memory=False,
)

df_filtered = df[
    (df["PseudoID"] == 71) & (df["dp001_record_plus_view_action"] == "paused")
]

print(len(df_filtered))

#3-2
import pandas as pd

df = pd.read_csv(
    "/content/edu_bigdata_imp1.csv",
    encoding="big5",
    low_memory=False,
)

##開始時間
df_filtered_start = df[df["PseudoID"] == 71]
df_filtered_start = df_filtered_start.dropna(subset=["dp001_review_start_time"])
s_start = pd.Series(pd.to_datetime(df_filtered_start["dp001_review_start_time"]))
dates_start = s_start.dt.date
dates_start = s_start.dt.strftime("%Y-%m-%d")
dates_start = dates_start.dropna()
unique_values_start = dates_start.unique()

##結束時間
df_filtered_end = df[df["PseudoID"] == 71]
df_filtered_end = df_filtered_end.dropna(subset=["dp001_review_end_time"])
s_end = pd.Series(pd.to_datetime(df_filtered_end["dp001_review_end_time"]))
dates_end = s_end.dt.date
dates_end = s_end.dt.strftime("%Y-%m-%d")
dates_end = dates_end.dropna()
unique_values_end = dates_end.unique()

##所有不重複日期
intersection = list(set(unique_values_start) & set(unique_values_end))
print("日期：", intersection)

#4-1
import pandas as pd

df = pd.read_csv(
    "/content/edu_bigdata_imp1.csv",
    encoding="big5",
    low_memory=False,
)

df_dp001 = df[df["PseudoID"] != 0]
most_viewed = df_dp001["dp001_review_sn"].value_counts().idxmax()
view_count = df_dp001["dp001_review_sn"].value_counts().max()

print(int(most_viewed), view_count)

#4-2
import pandas as pd

df = pd.read_csv(
    "/content/edu_bigdata_imp1.csv",
    encoding="big5",
    low_memory=False,
)

df_dp002 = df[df["dp002_extensions_alignment"] == '["十二年國民基本教育類"]']
data_count = df_dp002["dp002_extensions_alignment"].value_counts().max()

print(data_count)

#4-3
import pandas as pd

df = pd.read_csv(
    "/content/edu_bigdata_imp1.csv",
    encoding="big5",
    low_memory=False,
)

df_dp002 = df[df["PseudoID"] != 0]

counts = df_dp002["dp002_verb_display_zh_TW"].value_counts()

top_3 = counts.index[:3]

print(top_3)

#4-4
import pandas as pd

df = pd.read_csv(
    "/content/edu_bigdata_imp1.csv",
    encoding="big5",
    low_memory=False,
)

df_dp002 = df[df["dp002_extensions_alignment"] == '["校園職業安全"]']
data_count = df_dp002["dp002_extensions_alignment"].value_counts().max()

print(data_count)